### ISSUE TITLE
这个根本不是反序列化的时候发生的命令执行

### ISSUE THREAD

**Issue by OneSourceCat** [hengyunabc/dubbo-apache-commons-collections-bug#2]
不可否认，如果dubbo在RMI模式下，肯定是有漏洞的。
但是在hessian协议模式下，其实是序列化的时候发生的执行，也就是说是本地命令执行，并不能在远程服务器反序列化的过程中执行。具体原理可以调试一下hessian协议序列化map对象的过程，实际上是在对象序列化的时候执行的命令。

**Comment by hengyunabc** [comment]
配置文件里用的是java序列化，不是hessian。

``` xml
    <dubbo:protocol name="dubbo" port="20880" serialization="java"
        host="127.0.0.1" />
```
